[package]
name = "conduit-proxy-prometheus-export"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
publish = false

[dependencies]
bytes = "0.4"
prost = "0.3.0"
prost-types = "0.3.0"
prost-derive = "0.3.0"

[build-dependencies]
prost-build = "0.3.0"
